# Generated by Django 2.0.6 on 2018-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('description', models.CharField(max_length=4000)),
                ('location', models.CharField(max_length=200)),
                ('base_url', models.CharField(max_length=200)),
            ],
        ),
    ]
