# Generated by Django 2.0.6 on 2018-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='discovery_url',
            field=models.CharField(default='http://192.168.1.1', max_length=200),
        ),
        migrations.AddField(
            model_name='light',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=200),
        ),
        migrations.AlterField(
            model_name='light',
            name='base_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
